Rooplor/classcraft-backend

pom.xml, src/main/kotlin/com/rooplor/classcraftbackend/ClassCraftBackendApplication.kt, src/main/kotlin/com/rooplor/classcraftbackend/Controller/HelloController.kt, src/main/kotlin/com/rooplor/classcraftbackend/HelloController.kt, src/main/kotlin/com/rooplor/classcraftbackend/configuration/OpenApiConfig.kt
url: http://localhost:8080/swagger-ui/index.html
=> init-swagger

src/main/kotlin/com/rooplor/classcraftbackend/service/LoggerService.kt
**Add LoggerService**
After this, If we want to send a log to data source we can add it in this function.
Example
for dev if need to debug can print normal.
=> init loggerService

pom.xml, src/main/kotlin/com/rooplor/classcraftbackend/configuration/MinioConfig.kt, src/main/kotlin/com/rooplor/classcraftbackend/configuration/SwaggerConfig.kt, src/main/kotlin/com/rooplor/classcraftbackend/controllers/FileUploadController.kt, src/main/kotlin/com/rooplor/classcraftbackend/dtos/FileResponse.kt, src/main/kotlin/com/rooplor/classcraftbackend/dtos/Response.kt, src/main/kotlin/com/rooplor/classcraftbackend/services/FileUploadService.kt, src/main/resources/application.properties, src/test/kotlin/com/rooplor/classcraftbackend/controllers/FileUploadControllerTest.kt, src/test/kotlin/com/rooplor/classcraftbackend/services/FileUploadServiceTest.kt
https://nine0512.atlassian.net/jira/software/projects/RP/boards/1?selectedIssue=RP-22
=> [RP-22] Implement Minio file upload

src/main/kotlin/com/rooplor/classcraftbackend/controllers/UserController.kt, src/main/kotlin/com/rooplor/classcraftbackend/messages/ErrorMessages.kt, src/main/kotlin/com/rooplor/classcraftbackend/services/AuthService.kt, src/test/kotlin/com/rooplor/classcraftbackend/controllers/UserControllerTest.kt, src/test/kotlin/com/rooplor/classcraftbackend/services/AuthServiceTest.kt
https://nine0512.atlassian.net/jira/software/projects/RP/boards/1?selectedIssue=RP-32
=> [RP-32] Fix user can delete themselves

src/main/kotlin/com/rooplor/classcraftbackend/services/FileUploadService.kt, src/test/kotlin/com/rooplor/classcraftbackend/services/FileUploadServiceTest.kt
https://nine0512.atlassian.net/jira/software/projects/RP/boards/1?selectedIssue=RP-30
=> [RP-30] Change return file path for file service

src/main/kotlin/com/rooplor/classcraftbackend/configuration/SecurityConfig.kt, src/main/resources/application.properties
https://nine0512.atlassian.net/jira/software/projects/RP/boards/1?selectedIssue=RP-39
=> [RP-39] Create Dev profile for bypass jwt token

src/main/kotlin/com/rooplor/classcraftbackend/controllers/ClassController.kt, src/main/kotlin/com/rooplor/classcraftbackend/dtos/ClassListDTO.kt, src/main/kotlin/com/rooplor/classcraftbackend/dtos/InitClassDTO.kt, src/main/kotlin/com/rooplor/classcraftbackend/entities/Classroom.kt, src/main/kotlin/com/rooplor/classcraftbackend/entities/User.kt, src/main/kotlin/com/rooplor/classcraftbackend/messages/ErrorMessages.kt, src/main/kotlin/com/rooplor/classcraftbackend/repositories/ClassroomRepository.kt, src/main/kotlin/com/rooplor/classcraftbackend/services/AuthService.kt, src/main/kotlin/com/rooplor/classcraftbackend/services/ClassService.kt, src/main/kotlin/com/rooplor/classcraftbackend/services/UserService.kt, src/test/kotlin/com/rooplor/classcraftbackend/controllers/ClassroomControllerTest.kt, src/test/kotlin/com/rooplor/classcraftbackend/repositories/ClassroomRepositoryTest.kt, src/test/kotlin/com/rooplor/classcraftbackend/services/AuthServiceTest.kt, src/test/kotlin/com/rooplor/classcraftbackend/services/ClassroomServiceTest.kt, src/test/kotlin/com/rooplor/classcraftbackend/services/UserServiceTest.kt
https://nine0512.atlassian.net/jira/software/projects/RP/boards/1?selectedIssue=RP-31
=> [RP-31] Make Class relate with User

src/main/kotlin/com/rooplor/classcraftbackend/configuration/MinioConfig.kt, src/main/kotlin/com/rooplor/classcraftbackend/services/FileUploadService.kt, src/main/resources/application.properties, src/test/kotlin/com/rooplor/classcraftbackend/controllers/FileUploadControllerTest.kt, src/test/kotlin/com/rooplor/classcraftbackend/services/FileUploadServiceTest.kt
https://nine0512.atlassian.net/jira/software/projects/RP/boards/1?selectedIssue=RP-43
=> [RP-43] update file service to return reverse proxy link

src/main/kotlin/com/rooplor/classcraftbackend/controllers/FileUploadController.kt, src/main/kotlin/com/rooplor/classcraftbackend/services/FileUploadService.kt, src/test/kotlin/com/rooplor/classcraftbackend/controllers/FileUploadControllerTest.kt, src/test/kotlin/com/rooplor/classcraftbackend/services/FileUploadServiceTest.kt
https://nine0512.atlassian.net/jira/software/projects/RP/boards/1?selectedIssue=RP-51
=> [RP-51] Use only class Id for create minio folder

src/main/kotlin/com/rooplor/classcraftbackend/configuration/SecurityConfig.kt, src/main/kotlin/com/rooplor/classcraftbackend/constant/Age.kt, src/main/kotlin/com/rooplor/classcraftbackend/controllers/AuthController.kt, src/main/kotlin/com/rooplor/classcraftbackend/controllers/DevAuthController.kt, src/main/kotlin/com/rooplor/classcraftbackend/filters/DevJwtRequestFilter.kt, src/main/kotlin/com/rooplor/classcraftbackend/services/DevAuthService.kt, src/main/kotlin/com/rooplor/classcraftbackend/utils/JwtUtil.kt, src/test/kotlin/com/rooplor/classcraftbackend/controllers/AuthControllerTest.kt, src/test/kotlin/com/rooplor/classcraftbackend/controllers/DevAuthControllerTest.kt, src/test/kotlin/com/rooplor/classcraftbackend/services/DevAuthServiceTest.kt, src/test/kotlin/com/rooplor/classcraftbackend/utils/JwtUtilTest.kt
https://nine0512.atlassian.net/jira/software/projects/RP/boards/1?selectedIssue=RP-52
=> [RP-52] Create controller to get jwt token for dev environment

.gitignore, src/main/kotlin/com/rooplor/classcraftbackend/controllers/ClassController.kt, src/main/kotlin/com/rooplor/classcraftbackend/services/ClassService.kt, src/test/kotlin/com/rooplor/classcraftbackend/controllers/ClassroomControllerTest.kt, src/test/kotlin/com/rooplor/classcraftbackend/services/ClassroomServiceTest.kt
https://nine0512.atlassian.net/browse/RP-49
=> [RP-49] toggle stepper status backend

src/main/kotlin/com/rooplor/classcraftbackend/controllers/ClassController.kt, src/main/kotlin/com/rooplor/classcraftbackend/controllers/VenueController.kt
https://nine0512.atlassian.net/browse/RP-50
=> [RP-50] use global response for classroom backend

src/main/kotlin/com/rooplor/classcraftbackend/controllers/UserController.kt, src/test/kotlin/com/rooplor/classcraftbackend/controllers/UserControllerTest.kt
https://nine0512.atlassian.net/jira/software/projects/RP/boards/1?selectedIssue=RP-55
=> [RP-55] Create get user profile

src/main/kotlin/com/rooplor/classcraftbackend/controllers/ClassController.kt, src/test/kotlin/com/rooplor/classcraftbackend/controllers/ClassroomControllerTest.kt
https://nine0512.atlassian.net/jira/software/projects/RP/boards/1?selectedIssue=RP-56
=> [RP-56] merge '/api/class' and '/api/class/owners'

src/main/kotlin/com/rooplor/classcraftbackend/dtos/ClassListDTO.kt, src/main/kotlin/com/rooplor/classcraftbackend/dtos/InitClassDTO.kt, src/main/kotlin/com/rooplor/classcraftbackend/entities/Classroom.kt, src/main/kotlin/com/rooplor/classcraftbackend/services/ClassService.kt, src/test/kotlin/com/rooplor/classcraftbackend/controllers/ClassroomControllerTest.kt
https://nine0512.atlassian.net/jira/software/projects/RP/boards/1?selectedIssue=RP-54
=> [RP-54] Add instructor detail and cover image in class

src/main/kotlin/com/rooplor/classcraftbackend/controllers/VenueController.kt
https://nine0512.atlassian.net/jira/software/projects/RP/boards/1?selectedIssue=RP-70
=> [RP-70] Update venue controller to use global response

src/main/kotlin/com/rooplor/classcraftbackend/configuration/DevCorsConfig.kt, src/main/kotlin/com/rooplor/classcraftbackend/configuration/SecurityConfig.kt, src/main/kotlin/com/rooplor/classcraftbackend/controllers/DevAuthController.kt, src/main/kotlin/com/rooplor/classcraftbackend/services/DevAuthService.kt, src/main/resources/application.properties
https://nine0512.atlassian.net/jira/software/projects/RP/boards/1?selectedIssue=RP-69
=> [RP-69] Allow cors for dev, add profile pic for dev

src/main/kotlin/com/rooplor/classcraftbackend/controllers/ClassController.kt, src/main/kotlin/com/rooplor/classcraftbackend/entities/Classroom.kt, src/main/kotlin/com/rooplor/classcraftbackend/enums/Status.kt, src/main/kotlin/com/rooplor/classcraftbackend/services/ClassService.kt, src/test/kotlin/com/rooplor/classcraftbackend/controllers/ClassroomControllerTest.kt, src/test/kotlin/com/rooplor/classcraftbackend/services/ClassroomServiceTest.kt
https://nine0512.atlassian.net/browse/RP-58
=> [RP-58] Change stepper status into number

src/main/resources/templates/reservation.html
=> Improve CSS of reservation mail template

src/main/kotlin/com/rooplor/classcraftbackend/services/cookie/CookieService.kt, src/main/resources/application.properties, src/test/kotlin/com/rooplor/classcraftbackend/configs/TestConfig.kt, src/test/kotlin/com/rooplor/classcraftbackend/services/CookieServiceTest.kt
https://nine0512.atlassian.net/jira/software/projects/RP/boards/1?selectedIssue=RP-74
=> [RP-74] make cookie secure

src/main/kotlin/com/rooplor/classcraftbackend/controllers/ClassController.kt, src/main/kotlin/com/rooplor/classcraftbackend/entities/Classroom.kt, src/main/kotlin/com/rooplor/classcraftbackend/enums/VenueStatus.kt, src/main/kotlin/com/rooplor/classcraftbackend/services/ClassService.kt, src/test/kotlin/com/rooplor/classcraftbackend/controllers/ClassroomControllerTest.kt, src/test/kotlin/com/rooplor/classcraftbackend/services/ClassroomServiceTest.kt
let merge https://github.com/Rooplor/classcraft-backend/pull/45 first
=> [RP-37] Update Classroom relate with venue as list and change venueStatus to number

.github/workflows/deploy_prod.yml, .github/workflows/deploy_qa.yml, src/main/kotlin/com/rooplor/classcraftbackend/services/cookie/CookieService.kt, src/main/resources/application.properties
https://nine0512.atlassian.net/jira/software/projects/RP/boards/1?selectedIssue=RP-74
1. Add more config for cookie
2. Fix deploy yml not use lasted config
=> [RP-74-B] Add more config for cookie

pom.xml, src/main/kotlin/com/rooplor/classcraftbackend/controllers/FormController.kt, src/main/kotlin/com/rooplor/classcraftbackend/dtos/FormCreateDTO.kt, src/main/kotlin/com/rooplor/classcraftbackend/dtos/FormSubmissionDTO.kt, src/main/kotlin/com/rooplor/classcraftbackend/dtos/Question.kt, src/main/kotlin/com/rooplor/classcraftbackend/entities/Form.kt, src/main/kotlin/com/rooplor/classcraftbackend/entities/FormSubmission.kt, src/main/kotlin/com/rooplor/classcraftbackend/enums/FieldValidation.kt, src/main/kotlin/com/rooplor/classcraftbackend/helpers/FormHelper.kt, src/main/kotlin/com/rooplor/classcraftbackend/messages/ErrorMessages.kt, src/main/kotlin/com/rooplor/classcraftbackend/repositories/FormRepository.kt, src/main/kotlin/com/rooplor/classcraftbackend/repositories/FormSubmissionRepository.kt, src/main/kotlin/com/rooplor/classcraftbackend/services/AuthService.kt, src/main/kotlin/com/rooplor/classcraftbackend/services/ClassService.kt, src/main/kotlin/com/rooplor/classcraftbackend/services/FormService.kt, src/main/kotlin/com/rooplor/classcraftbackend/services/FormSubmissionService.kt, src/test/kotlin/com/rooplor/classcraftbackend/controllers/FormControllerTest.kt, src/test/kotlin/com/rooplor/classcraftbackend/helpers/FormHelperTest.kt, src/test/kotlin/com/rooplor/classcraftbackend/repositories/FormRepositoryTest.kt, src/test/kotlin/com/rooplor/classcraftbackend/repositories/FormSubmissionRepositoryTest.kt, src/test/kotlin/com/rooplor/classcraftbackend/services/AuthServiceTest.kt, src/test/kotlin/com/rooplor/classcraftbackend/services/ClassroomServiceTest.kt, src/test/kotlin/com/rooplor/classcraftbackend/services/FormServiceTest.kt, src/test/kotlin/com/rooplor/classcraftbackend/services/FormSubmissionServiceTest.kt
https://nine0512.atlassian.net/jira/software/projects/RP/boards/1?selectedIssue=RP-76
Create form service
=> [RP-76] Create form service

src/main/kotlin/com/rooplor/classcraftbackend/controllers/FileUploadController.kt, src/main/kotlin/com/rooplor/classcraftbackend/services/FileUploadService.kt
https://nine0512.atlassian.net/jira/software/projects/RP/boards/1?selectedIssue=RP-78
=> Change classId to fileCategory

src/main/kotlin/com/rooplor/classcraftbackend/controllers/ClassController.kt, src/main/kotlin/com/rooplor/classcraftbackend/entities/Classroom.kt, src/main/kotlin/com/rooplor/classcraftbackend/entities/Venue.kt, src/main/kotlin/com/rooplor/classcraftbackend/services/ClassService.kt, src/main/kotlin/com/rooplor/classcraftbackend/services/VenueService.kt, src/main/kotlin/com/rooplor/classcraftbackend/types/DateWithVenue.kt, src/main/resources/templates/reservation.html, src/test/kotlin/com/rooplor/classcraftbackend/controllers/ClassroomControllerTest.kt, src/test/kotlin/com/rooplor/classcraftbackend/repositories/VenueRepositoryTest.kt, src/test/kotlin/com/rooplor/classcraftbackend/services/ClassroomServiceTest.kt
merge https://github.com/Rooplor/classcraft-backend/pull/51 first
=> Change attr venue from `name` to `room`

src/main/kotlin/com/rooplor/classcraftbackend/controllers/ClassController.kt, src/main/kotlin/com/rooplor/classcraftbackend/repositories/ClassroomRepository.kt, src/main/kotlin/com/rooplor/classcraftbackend/services/ClassService.kt, src/test/kotlin/com/rooplor/classcraftbackend/controllers/ClassroomControllerTest.kt, src/test/kotlin/com/rooplor/classcraftbackend/repositories/ClassroomRepositoryTest.kt, src/test/kotlin/com/rooplor/classcraftbackend/services/ClassroomServiceTest.kt
https://nine0512.atlassian.net/jira/software/projects/RP/boards/1?selectedIssue=RP-80
=> [RP-80] Create search endpoint

src/main/kotlin/com/rooplor/classcraftbackend/controllers/VenueController.kt, src/test/kotlin/com/rooplor/classcraftbackend/controllers/VenueControllerTest.kt
https://nine0512.atlassian.net/jira/software/projects/RP/boards/1?selectedIssue=RP-130
=> [RP-130] Get venue by Id

src/main/kotlin/com/rooplor/classcraftbackend/dtos/FormCreateDTO.kt, src/main/kotlin/com/rooplor/classcraftbackend/entities/Form.kt
https://nine0512.atlassian.net/jira/software/projects/RP/boards/1?selectedIssue=RP-137
=> Change openDate and closeDate to optional

src/main/kotlin/com/rooplor/classcraftbackend/controllers/FormController.kt, src/main/kotlin/com/rooplor/classcraftbackend/helpers/ClassroomHelper.kt, src/main/kotlin/com/rooplor/classcraftbackend/helpers/FormHelper.kt, src/main/kotlin/com/rooplor/classcraftbackend/services/ClassService.kt, src/main/kotlin/com/rooplor/classcraftbackend/services/FormService.kt, src/test/kotlin/com/rooplor/classcraftbackend/controllers/FormControllerTest.kt, src/test/kotlin/com/rooplor/classcraftbackend/helpers/ClassroomHelperTest.kt, src/test/kotlin/com/rooplor/classcraftbackend/helpers/FormHelperTest.kt, src/test/kotlin/com/rooplor/classcraftbackend/services/ClassroomServiceTest.kt, src/test/kotlin/com/rooplor/classcraftbackend/services/FormServiceTest.kt
https://nine0512.atlassian.net/jira/software/projects/RP/boards/1?selectedIssue=RP-136
Create validation when create and update classroom
=> [RP-136] Create validation for create and update classroom

src/main/kotlin/com/rooplor/classcraftbackend/services/ClassService.kt, src/test/kotlin/com/rooplor/classcraftbackend/services/ClassroomServiceTest.kt
https://nine0512.atlassian.net/jira/software/projects/RP/boards/1/backlog?selectedIssue=RP-140
=> [RP-140] Create form automatically after create classroom

src/main/kotlin/com/rooplor/classcraftbackend/controllers/FormController.kt, src/main/kotlin/com/rooplor/classcraftbackend/entities/FormSubmission.kt, src/main/kotlin/com/rooplor/classcraftbackend/enums/AttendeesStatus.kt, src/main/kotlin/com/rooplor/classcraftbackend/services/FormSubmissionService.kt, src/test/kotlin/com/rooplor/classcraftbackend/controllers/FormControllerTest.kt, src/test/kotlin/com/rooplor/classcraftbackend/services/FormSubmissionServiceTest.kt
https://nine0512.atlassian.net/jira/software/projects/RP/boards/1/backlog?selectedIssue=RP-142
=> Add AttendeesStatus and create endpoint to update AttendeesStatus

src/main/kotlin/com/rooplor/classcraftbackend/controllers/FormController.kt, src/main/kotlin/com/rooplor/classcraftbackend/dtos/UserDetailDTO.kt, src/main/kotlin/com/rooplor/classcraftbackend/entities/FormSubmission.kt, src/main/kotlin/com/rooplor/classcraftbackend/services/FormSubmissionService.kt, src/test/kotlin/com/rooplor/classcraftbackend/controllers/FormControllerTest.kt, src/test/kotlin/com/rooplor/classcraftbackend/services/FormSubmissionServiceTest.kt
https://nine0512.atlassian.net/jira/software/projects/RP/boards/1/backlog?selectedIssue=RP-151
=> [RP-151] add userDetail in formSubmission and create endpoint for get user who enrolled in this class

src/main/kotlin/com/rooplor/classcraftbackend/controllers/ClassController.kt, src/main/kotlin/com/rooplor/classcraftbackend/dtos/ClassroomResponse.kt, src/main/kotlin/com/rooplor/classcraftbackend/dtos/FormCreateDTO.kt, src/test/kotlin/com/rooplor/classcraftbackend/controllers/ClassroomControllerTest.kt, src/test/kotlin/com/rooplor/classcraftbackend/controllers/FormControllerTest.kt
https://nine0512.atlassian.net/jira/software/projects/RP/boards/1/backlog?selectedIssue=RP-162
=> [RP-162] Update get all classroom endpoint to show enroll detail

src/main/kotlin/com/rooplor/classcraftbackend/controllers/FileUploadController.kt, src/main/kotlin/com/rooplor/classcraftbackend/dtos/FileResponse.kt
https://nine0512.atlassian.net/jira/software/projects/RP/boards/1/backlog?selectedIssue=RP-164
Old res:
```
{
"success": true,
"result": {
"url":  "file url"
},
"error": null
}
```
New res:
```
{
"success": true,
"result": {
"urls": [
"File url1",
"File url2"
]
},
"error": null
}
```
=> [RP-164] Modify fileUpload endpoint to upload multiple file

src/main/kotlin/com/rooplor/classcraftbackend/controllers/FormController.kt, src/main/kotlin/com/rooplor/classcraftbackend/dtos/FormSubmissionDTO.kt, src/main/kotlin/com/rooplor/classcraftbackend/enums/AttendeesStatus.kt, src/test/kotlin/com/rooplor/classcraftbackend/controllers/FormControllerTest.kt
https://nine0512.atlassian.net/jira/software/projects/RP/boards/1/backlog?selectedIssue=RP-172
=> [RP-172] Update AttendeesStatus enum map with number and update formSubmission controller to use DTO

src/main/kotlin/com/rooplor/classcraftbackend/controllers/FormController.kt, src/main/kotlin/com/rooplor/classcraftbackend/entities/FormSubmission.kt, src/main/kotlin/com/rooplor/classcraftbackend/services/FormSubmissionService.kt, src/main/kotlin/com/rooplor/classcraftbackend/types/Attendees.kt, src/test/kotlin/com/rooplor/classcraftbackend/controllers/FormControllerTest.kt, src/test/kotlin/com/rooplor/classcraftbackend/services/FormSubmissionServiceTest.kt
https://nine0512.atlassian.net/jira/software/projects/RP/boards/1/backlog?selectedIssue=RP-173
=> [RP-173] Support multiple date check-in

src/main/kotlin/com/rooplor/classcraftbackend/repositories/FormSubmissionRepository.kt, src/main/kotlin/com/rooplor/classcraftbackend/services/ClassService.kt, src/main/kotlin/com/rooplor/classcraftbackend/services/FormService.kt, src/test/kotlin/com/rooplor/classcraftbackend/services/ClassroomServiceTest.kt, src/test/kotlin/com/rooplor/classcraftbackend/services/FormServiceTest.kt
https://nine0512.atlassian.net/jira/software/projects/RP/boards/1/backlog?selectedIssue=RP-176
=> [RP-176] Remove related date after delete classroom

src/main/kotlin/com/rooplor/classcraftbackend/messages/ErrorMessages.kt, src/main/kotlin/com/rooplor/classcraftbackend/repositories/FormSubmissionRepository.kt, src/main/kotlin/com/rooplor/classcraftbackend/services/ClassService.kt, src/main/kotlin/com/rooplor/classcraftbackend/services/FormService.kt, src/test/kotlin/com/rooplor/classcraftbackend/services/ClassroomServiceTest.kt, src/test/kotlin/com/rooplor/classcraftbackend/services/FormServiceTest.kt
https://nine0512.atlassian.net/jira/software/projects/RP/boards/1/backlog?selectedIssue=RP-177
merge RP-176 first
=> [RP-177] Remove approved venue and form submission when update date

src/main/kotlin/com/rooplor/classcraftbackend/services/FormSubmissionService.kt, src/main/kotlin/com/rooplor/classcraftbackend/types/Attendees.kt, src/test/kotlin/com/rooplor/classcraftbackend/services/FormSubmissionServiceTest.kt
https://nine0512.atlassian.net/jira/software/projects/RP/boards/1/backlog?selectedIssue=RP-182
- Support UTF-8
- Display "Registration Status" in form "Approved" and "Pending"
- Split attendees status follow by days and add "Check-in at" detail
- Add feedback
=> [RP-182] Update csv data

src/main/kotlin/com/rooplor/classcraftbackend/controllers/ClassController.kt, src/main/kotlin/com/rooplor/classcraftbackend/controllers/DashboardController.kt, src/main/kotlin/com/rooplor/classcraftbackend/controllers/FormController.kt, src/main/kotlin/com/rooplor/classcraftbackend/controllers/UserController.kt, src/main/kotlin/com/rooplor/classcraftbackend/controllers/VenueController.kt, src/main/kotlin/com/rooplor/classcraftbackend/messages/ErrorMessages.kt, src/main/kotlin/com/rooplor/classcraftbackend/services/ClassService.kt, src/main/kotlin/com/rooplor/classcraftbackend/services/DashboardService.kt, src/main/kotlin/com/rooplor/classcraftbackend/services/VenueService.kt, src/test/kotlin/com/rooplor/classcraftbackend/controllers/ClassroomControllerTest.kt, src/test/kotlin/com/rooplor/classcraftbackend/controllers/FormControllerTest.kt, src/test/kotlin/com/rooplor/classcraftbackend/controllers/UserControllerTest.kt
https://nine0512.atlassian.net/jira/software/projects/RP/boards/1/backlog?selectedIssue=RP-184
=> Update response code to follow API principle

src/main/kotlin/com/rooplor/classcraftbackend/controllers/ReopenRequestController.kt, src/main/kotlin/com/rooplor/classcraftbackend/repositories/ReopenRequestRepository.kt, src/main/kotlin/com/rooplor/classcraftbackend/services/ReopenRequestService.kt, src/test/kotlin/com/rooplor/classcraftbackend/controllers/ReopenRequestControllerTest.kt, src/test/kotlin/com/rooplor/classcraftbackend/repositories/ReopenRequestRepositoryTest.kt, src/test/kotlin/com/rooplor/classcraftbackend/services/ReopenRequestServiceTest.kt
=> Add request existence check and user request retrieval endpoints
